### ISSUE TITLE
Blank screen launching prompt tracer the 2nd time

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-prompt-tsx#110]
In short, I'm doing the following:
* add the HTML Tracer
* render a prompt
* show the HTML
* dispose of that tracer
* render a new prompt with a new HTML Tracer
* show the HTML

The 2nd time I do this, I get a blank screen and:
![Image](https://github.com/user-attachments/assets/cacca703-5f8c-42df-80de-d8349bde42a4)

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-prompt-tsx/pull/114
