### ISSUE TITLE
Compress cl100k_base.tiktoken

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-prompt-tsx#39]
Testing https://github.com/microsoft/vscode-copilot/issues/5840

The tiktoken file format associates a token with an incrementing id:
```
IQ== 0
Ig== 1
Iw== 2
JA== 3
JQ== 4
Jg== 5
Jw== 6
KA== 7
KQ== 8
Kg== 9
Kw== 10
LA== 11
LQ== 12
Lg== 13
Lw== 14
MA== 15
MQ== 16
Mg== 17
...
```

Removing the derivable id decreases the file size from 1.69MB to 1.13MB.
Also, the line ending style of this file could be a problem, as on windows, this repository is checked out with CR LF.

**Comment by connor4312** [comment]
This library no longer ships the tiktoken dictionary, and we now compress the dictionary shipped in the copilot extension.

For other readers, we do basically what my code snippet above does ^ I experimented with some fancier ways to compress the dictionary, but the benefits were marginal and complexity much higher over the simple encoding above.
