### ISSUE TITLE
Embed cl100k_base.tiktoken in a js file

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-prompt-tsx#42]
Testing https://github.com/microsoft/vscode-copilot/issues/5840

If you would embed the tiktoken file content in a js/ts file, bundlers would automatically do the right thing.
This embedding could be generated from the tiktoken file in the build script.

Advantages:
* Works with and without bundlers
* No need for the `Building your extension with @vscode/prompt-tsx` chapter in the readme
* Library can be used to build vscode-web extensions in the future (which would currently not work)

Disadvantages:
* Slightly more complicated build step
* VS Code extensions cannot load source files asynchronously at the moment (no support for `import(./tokens).then(x => ...)`)

**Comment by connor4312** [comment]
No longer shipped with the library
